apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openshift-servicemesh
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: App bundle for installing OpenShift Service Mesh and dependancies
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
