apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openshift-servicemesh
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Deploy Operators for OpenShift ServiceMesh
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-servicemesh
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
#    namespace: openshift-operators-redhat
    server: https://kubernetes.default.svc
  project: openshift-servicemesh
  source:
    path: operators/OpenShift-ServiceMesh/base
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
