apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-product
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-distributed-tracing
    server: https://kubernetes.default.svc
  project: openshift-servicemesh
  source:
    path: operators/jaeger/overlays
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true