apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bookinfo
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Deploy Bookinfo ServiceMesh
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
#    namespace: openshift-operators-redhat
    server: https://kubernetes.default.svc
  project: bookinfo
  source:
    path: applications/bookinfo/base
    repoURL: https://github.com/nreilly-rhn/GitOps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true