apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Jaeger.v1.jaegertracing.io
    argocd.argoproj.io/sync-wave: "0"
  name: openshift-distributed-tracing
  namespace: openshift-distributed-tracing
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Elasticsearch.v1.logging.openshift.io,Kibana.v1.logging.openshift.io
    argocd.argoproj.io/sync-wave: "0"
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat
spec: {}